module.exports = {
    content: [
        './index.html',
        './src/**/*.{js,ts,jsx,tsx,css,md,mdx,html,json,scss}',
    ],
    prefix: '',
    important: false,
    separator: ':',
    theme: {
        gridTemplateAreas: {
            'md-private-layout': [
                'header header header header',
                'sidebar main main main',
                'sidebar footer footer footer',
            ],
            'desktop-layout': [
                'header header header header',
                'sidebar main main main',
                'sidebar footer footer footer',
            ],
            'tablet-layout': [
                'header header header header',
                'sidebar . main main',
                'sidebar footer footer footer',
            ],
            'mobile-layout': [
                'header header header header',
                'main main main main',
                'footer footer footer footer',
            ],
        },
        screens: {
            xs: '320px',
            sm: '640px',
            md: '768px',
            lg: '1024px',
            xl: '1280px',
        },
        spacing: {
            'px': '1px',
            '0': '0',
            '1': '0.25rem',
            '2': '0.5rem',
            '3': '0.75rem',
            '4': '1rem',
            '5': '1.25rem',
            '6': '1.5rem',
            '8': '2rem',
            '9': '2.2rem',
            '10': '2.5rem',
            '12': '3rem',
            '13': '3.3rem',
            '14': '3.5rem',
            '15': '3.75rem',
            '16': '4rem',
            '18': '4.5rem',
            '20': '5rem',
            '24': '6rem',
            '32': '8rem',
            '40': '10rem',
            '48': '12rem',
            '56': '14rem',
            '58': '15.35rem',
            '64': '16rem',
            '72': '24rem',
            '128': '32rem',
            '1/2': '50%',
            '1/3': '33.333333%',
            '2/3': '66.666667%',
            '1/4': '25%',
            '2/4': '50%',
            '3/4': '75%',
            '1/5': '20%',
            '2/5': '40%',
            '3/5': '60%',
            '4/5': '80%',
            '1/6': '16.666667%',
            '2/6': '33.333333%',
            '3/6': '50%',
            '4/6': '66.666667%',
            '5/6': '83.333333%',
            '1/12': '8.333333%',
            '2/12': '16.666667%',
            '3/12': '25%',
            '4/12': '33.333333%',
            '5/12': '41.666667%',
            '6/12': '50%',
            '7/12': '58.333333%',
            '8/12': '66.666667%',
            '9/12': '75%',
            '10/12': '83.333333%',
            '11/12': '91.666667%',
            'full': '100%',
        },
        borderRadius: {
            'none': '0',
            'sm': '0.125rem',
            'default': '0.25rem',
            'md': '0.375rem',
            'lg': '0.5rem',
            'lg-md': '1rem',
            'xl': '2rem',
            'full': '9999px',
        },
        fontFamily: {
            sans: [
                'system-ui',
                '-apple-system',
                'BlinkMacSystemFont',
                '"Segoe UI"',
                'Roboto',
                '"Helvetica Neue"',
                'Arial',
                '"Noto Sans"',
                'sans-serif',
                '"Apple Color Emoji"',
                '"Segoe UI Emoji"',
                '"Segoe UI Symbol"',
                '"Noto Color Emoji"',
            ],
            serif: [ 'Georgia', 'Cambria', '"Times New Roman"', 'Times', 'serif' ],
            mono: [
                'Menlo',
                'Monaco',
                'Consolas',
                '"Liberation Mono"',
                '"Courier New"',
                'monospace',
            ],
        },
        gridTemplateColumns: {
            'none': 'none',
            '1': 'repeat(1, minmax(0, 1fr))',
            '2': 'repeat(2, minmax(0, 1fr))',
            '3': 'repeat(3, minmax(0, 1fr))',
            '4': 'repeat(4, minmax(0, 1fr))',
            '5': 'repeat(5, minmax(0, 1fr))',
            '6': 'repeat(6, minmax(0, 1fr))',
            '7': 'repeat(7, minmax(0, 1fr))',
            '8': 'repeat(8, minmax(0, 1fr))',
            '9': 'repeat(9, minmax(0, 1fr))',
            '10': 'repeat(10, minmax(0, 1fr))',
            '11': 'repeat(11, minmax(0, 1fr))',
            '12': 'repeat(12, minmax(0, 1fr))',
            '13': '15% auto',
            'desktop-layout': 'min-content',
        },
        keyframes: {
            spin: {
                to: { transform: 'rotate(360deg)' },
            },
            ping: {
                '75%, 100%': { transform: 'scale(2)', opacity: '0' },
            },
            pulse: {
                '50%': { opacity: '.5' },
            },
            bounce: {
                '0%, 100%': {
                    transform: 'translateY(-25%)',
                    animationTimingFunction: 'cubic-bezier(0.8,0,1,1)',
                },
                '50%': {
                    transform: 'none',
                    animationTimingFunction: 'cubic-bezier(0,0,0.2,1)',
                },
            },
        },
        extends: {
            animation: {
                fade: 'fadeIn 5s ease-in-in',
            },
        },
    },
    corePlugins: {},
    plugins: [
        require( '@savvywombat/tailwindcss-grid-areas' ),
    ],
};
